

# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
# pandoc_version: 1.16 # crashing because it is trying to fetch .deb from github (not existant url)
sudo: required 		# required for apt-get
cache: packages 	# caching the package to install is a speed-up
warnings_are_errors: false
bioc_required: true


os:
  - linux
  - osx

#dist: xenial #not working because only trusty is supported

dist: trusty

#addons:
#  apt: # ignored if not linux BUT we need with-fortran... How to?
#    packages:
#      - libnetcdf-dev
r:
  - release # currently 3.3.0
  # - bioc-devel # not necessary. it duplicates again the working nodes
ruby:
  - release # for brew
# brew_packages:
#   - gcc
#
#
notifications:
  email: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap homebrew/science; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then sudo chown -R $(whoami) /usr/local; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm '/usr/local/bin/gfortran' ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc; fi
  - if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then brew link --overwrite --force cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install netcdf --with-fortran --without-test; fi # must be specified
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install arpack; fi # must be specified
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  rm '/usr/local/bin/pandoc'; fi # must be specified
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  rm '/usr/local/share/man/man1/pandoc.1'; fi # must be specified
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pandoc; fi # must be specified
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install fftw; fi # must be specified
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install open-mpi; fi # must be specified
  
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libnetcdff5; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libnetcdf-dev; fi # must be specified
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libarpack2-dev; fi # must be specified
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install netcdf-bin; fi # must be specified
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install pandoc; fi # must be specified
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libblas-common; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y liblapack-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libfftw3-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libfftw3-bin; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libopenmpi-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y openmpi-bin; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  apt-get install -y automake; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  apt-get install -y gfortran; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  apt-get install -y libnetcdff6; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  apt-get install -y libnetcdff-dev; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  apt-get install -y netcdf-bin; fi



# the following seems not necessary
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"; fi


# The following are useful if you are building on multiple testing machines. If only apt-get installation is needed it is possible to use the addons command (see before)
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libnetcdf-dev ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libnetcdff-dev ; fi

bioc_packages:
  - AnnotationDbi
  - impute
  - GO.db
  - preprocessCore
  
r_github_packages:
  - jimhester/covr
  - cran/WGCNA
  - cran/PairViz # it can not be seen by mac?
  - rstudio/rmarkdown

r-packages:
  - bio3d
  - ggplot2
  - parallel
  - data.table
  - Rcpp
  - gplots
  - grDevices
  - graphics
  - outliers
  - pcaPP
  - prospectr
  - splus2R
  - stats
  - expm
  - Hmisc
  - sfsmisc
  - plotly
  - ggfortify
  - Rtsne
  - TSA
#  - PairViz
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; WGCNA ; fi 

#output: # pandoc must be installed with dev options from github
#  html_document: 
#    smart: false

after_script:
  - ls -lah
  - FILE=$(ls -1t *.tar.gz | head -n 1)

after_success:
  - Rscript -e 'library(covr); codecov()'

r_build_args: --no-manual
r_check_args: --as-cran --no-manual 

